name: Sync Fork with Upstream
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Git user
        run: |
          git config --global user.name "Arne Tarara"
          git config --global user.email "arne@green-coding.io"

      - name: Add remote repository
        run: |
          git remote add upstream https://github.com/nextcloud/server
          git fetch upstream master

      - name: Check for updates
        run: |
          CHANGES=$(git rev-list HEAD..upstream/master --count)
          if [ "$CHANGES" -gt 0 ]; then
            echo "Updating fork master branch..."
            git checkout master
            git merge --ff-only upstream/master
            git push

            echo "Bringing in changes from Green Metrics Tool Branch..."
            git checkout green-metrics-tool
            git pull
            git checkout master
            git merge --ff-only green-metrics-tool
            git push
          else
            echo "No updates from the original repository."
          fi
